/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreditEntity } from './creditEntity';
import { RepaymentEntity } from './repaymentEntity';


export interface Account { 
    id?: number;
    code?: string;
    description?: string;
    owner?: string;
    amountbalance?: number;
    amountconsumed?: number;
    amountRest?: number;
    calculatedAmountbalance?: number;
    calculatedAmountconsumed?: number;
    calculatedAmountRest?: number;
    creditsGiven?: Array<CreditEntity>;
    creditsReceived?: Array<CreditEntity>;
    repaymentsReceived?: Array<RepaymentEntity>;
    repaymentsMade?: Array<RepaymentEntity>;
}

