/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreditStatus } from './creditStatus';
import { Account } from './account';
import { Purpose } from './purpose';


export interface Spending { 
    id?: number;
    code?: string;
    notes?: string;
    amountToSpend?: number;
    actionDate?: string;
    purpose?: Purpose;
    creditStatus?: CreditStatus;
    account?: Account;
}

