/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserGender } from './userGender';
import { Country } from './country';
import { City } from './city';
import { UserStatus } from './userStatus';
import { UserType } from './userType';


export interface User { 
    id?: number;
    name?: string;
    age?: string;
    description?: string;
    zipcode?: number;
    note?: string;
    contactNumber?: string;
    email?: string;
    password?: string;
    userType?: UserType;
    userGender?: UserGender;
    userStatus?: UserStatus;
    city?: City;
    country?: Country;
}

