/// <reference types="@angular/localize" />

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';

import { registerLicense } from '@syncfusion/ej2-base';

// Registering Syncfusion license key
registerLicense("MzE3OTA3N0AzMjM0MmUzMDJlMzBIc2VzQ1NvRXJTd01EQ1BnbHlwVzk2VFZ4dm1malZ5UlhqaWtvVkhPTHFjPQ==;MzE3OTA3OEAzMjM0MmUzMDJlMzBiWTJXRWJNeGNRWHhlcjlXdkdmOXRVTzRRLzV0Ujl6VDV3RkxFQjhyZ3ZjPQ==;Mgo+DSMBaFt7QHFqUUdrXVNbdV5dVGpAd0N3RGlcdlR1fUUmHVdTRHRbQl5hS3xTdkZiW3lfcHE=;Mgo+DSMBPh8sVXJwS0d+WFBPd11dXmJWd1p/THNYflR1fV9DaUwxOX1dQl9nSX1RdEdjWXxfcnJXQWI=;ORg4AjUWIQA/Gnt2UVhhQlVFfV5AQmBIYVp/TGpJfl96cVxMZVVBJAtUQF1hTX5QdEdhWX9dcXZTQ2hZ;NRAiBiAaIQQuGjN/V0J+XU9Ad1RDX3xKf0x/TGpQb19xflBPallYVBYiSV9jS3pTdUdhW39ec3VXQGhfUA==;MzE3OTA4M0AzMjM0MmUzMDJlMzBMZkhWbk81dE5jQ0VoM2lpelovTUtaL1g0QWZUSUdocUIwU0pBYjFtN3dJPQ==;MzE3OTA4NEAzMjM0MmUzMDJlMzBjeFV2UGFId3hOcU81clJEcS9aN2hkZkZheGJGR1VMVzhsTmZCSm41RExZPQ==;Mgo+DSMBMAY9C3t2UVhhQlVFfV5AQmBIYVp/TGpJfl96cVxMZVVBJAtUQF1hTX5QdEdhWX9dcXZSTmBb;MzE3OTA4NkAzMjM0MmUzMDJlMzBXc3NUbDNIRUdZWXJuNU81NjhWM0pWbmFxU2k4cWt3cEl4MVhKZmN6dEI4PQ==;MzE3OTA4N0AzMjM0MmUzMDJlMzBsRTNGcm5Zbzh0ZGxQdkxnMU9qMmttWDNkSFRNL2p0MktEK1Q4RllRV1RNPQ==;MzE3OTA4OEAzMjM0MmUzMDJlMzBMZkhWbk81dE5jQ0VoM2lpelovTUtaL1g0QWZUSUdocUIwU0pBYjFtN3dJPQ==");

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
